# Generated by Django 4.2.13 on 2024-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image1', models.ImageField(upload_to='carousel_images/')),
                ('caption', models.CharField(max_length=250)),
                ('cap_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('image1', models.ImageField(upload_to='product_images/')),
                ('image2', models.ImageField(upload_to='product_images/')),
                ('image3', models.ImageField(upload_to='product_images/')),
                ('image4', models.ImageField(upload_to='product_images/')),
                ('image_title1', models.CharField(max_length=250)),
                ('image_title2', models.CharField(max_length=250)),
                ('image_title3', models.CharField(max_length=250)),
                ('image_title4', models.CharField(max_length=250)),
            ],
        ),
    ]
