# Generated by Django 4.2.13 on 2024-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registrationmodel_about_registrationmodel_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationmodel',
            name='About',
        ),
    ]
