# Generated by Django 5.0.6 on 2024-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_productmodel_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentdataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('Amount_paid', models.IntegerField(null=True)),
                ('Amount_due', models.IntegerField(null=True)),
                ('Currency', models.CharField(max_length=100, null=True)),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('Status', models.CharField(max_length=30, null=True)),
                ('Attempts', models.IntegerField(null=True)),
                ('Notes', models.TextField(null=True)),
                ('Created_at', models.CharField(max_length=255, null=True)),
                ('Payment_Id', models.CharField(max_length=255, null=True)),
                ('Order_id', models.CharField(max_length=255, null=True)),
                ('Signature', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='Prod_Name',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=254, null=True),
        ),
    ]
