# Generated by Django 5.0.6 on 2024-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_receipt_paymentdatamodel_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdatamodel',
            name='Datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdatamodel',
            name='Payment_Id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentdatamodel',
            name='Signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
