# Generated by Django 5.0.6 on 2024-06-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_paymentdatamodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdatamodel',
            name='Payment_Id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdatamodel',
            name='Signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
