# Generated by Django 5.0.6 on 2024-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_paymentdatamodel_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='About',
            field=models.TextField(null=True),
        ),
    ]
