# Generated by Django 5.0.6 on 2024-06-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_registrationmodel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='Username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
