# Generated by Django 5.0.6 on 2024-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_registrationmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='Profile',
            field=models.ImageField(null=True, upload_to=True),
        ),
    ]
