# Generated by Django 5.0.6 on 2024-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_registrationmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='Birthday',
            field=models.DateField(null=True),
        ),
    ]
