# Generated by Django 5.0.6 on 2024-06-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_registrationmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Product_Type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
