# Generated by Django 5.0.6 on 2024-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_purchaseproduct_productmodel_prod_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Prod_Net_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Prod_gross_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Prod_tax',
            field=models.IntegerField(null=True),
        ),
    ]
