# Generated by Django 5.0.6 on 2024-06-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_productmodel_prod_net_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Prod_Price',
        ),
    ]
