# Generated by Django 5.0.6 on 2024-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_productmodel_prod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Prod_Price',
            field=models.IntegerField(null=True),
        ),
    ]
