# Generated by Django 5.0.6 on 2024-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_productmodel_prod_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_id', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('Customer_id', models.CharField(blank=True, max_length=255)),
                ('Order_id', models.CharField(blank=True, max_length=255)),
                ('Payment_id', models.CharField(blank=True, max_length=255)),
                ('Gross_amount', models.IntegerField(blank=True)),
                ('Tax_amount', models.IntegerField(blank=True)),
                ('Amount', models.IntegerField(blank=True)),
                ('Amount_paid', models.IntegerField(blank=True)),
                ('Amount_due', models.IntegerField(blank=True)),
                ('Currency', models.CharField(blank=True, max_length=255)),
                ('Billing_address', models.TextField(blank=True)),
                ('Shipping_address', models.TextField(blank=True)),
                ('Billingtime', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
