# Generated by Django 5.0.6 on 2024-06-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_invoicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Order_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paymentdatamodel'),
        ),
        migrations.AlterField(
            model_name='paymentdatamodel',
            name='Created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='Order_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paymentdatamodel'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='Purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
