# Generated by Django 5.0.6 on 2024-06-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_invoicemodel_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='Order_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.purchaseproduct'),
        ),
    ]
