# Generated by Django 5.0.6 on 2024-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_invoicemodel_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdatamodel',
            name='Datetime',
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='Order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='Order_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
