# Generated by Django 5.0.6 on 2024-06-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_paymentdatamodel_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='Prod_Net_amount',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='prod_color',
            new_name='Prod_color',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='Prod_gross_amount',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='Prod_tax',
        ),
        migrations.AddField(
            model_name='paymentdatamodel',
            name='Prod_Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='Prod_Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentdatamodel',
            name='Created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdatamodel',
            name='Datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
