# Generated by Django 5.0.6 on 2024-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_prod_net_amount_productmodel_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='Invoice_pdf',
            field=models.FileField(null=True, upload_to='invoice_pdf/'),
        ),
    ]
