# Generated by Django 5.0.6 on 2024-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_invoicemodel_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='Payment_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='Invoice_pdf',
            field=models.FileField(null=True, upload_to='../invoice_pdf/'),
        ),
    ]
