# Generated by Django 5.0.6 on 2024-06-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_invoicemodel_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
